version: "2"

services:
  mariadb:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=composeddb
      - MYSQL_USER=hello
      - MYSQL_PASSWORD=there
    ports:
      - 3306:3306
    volumes:
      - maridb-volume:/docker-entrypoint-initdb.d
      - maridb-volume:/var/lib/mysql
  web:
    image: barthik/docker-compose:1.0.3-SNAPSHOT
    depends_on:
      - mariadb
    ports:
      - 9090:8080
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=composeddb
      - DATABASE_USER=hello
      - DATABASE_PASSWORD=there

volumes:
  maridb-volume: